### ISSUE TITLE
word "about" is never matched

### ISSUE THREAD

**Issue by pdeona** [weixsong/elasticlunr.js#101]
https://codepen.io/pdeona/pen/VgVLQg?editors=0010

Using this lib via the gatsby plugin and noticed the results weren't quite what was expected. i created this pen using only elasticlunr and my exact config, with some test data and confirmed - the term `About` is never matched, for any search terms i could come up with. I would imagine this effects quite a few people but didn't see an existing issue.

edit: stopWordFilter is disabled.

**Comment by srenauld** [comment]
This was not an issue with the library itself, but with your usage of it. [this codepen fork](https://codepen.io/srenauld/pen/mvQqEe?editors=1010) illustrates this.

Since `elasticlunr` does not keep the entire document anywhere beyond the fields you've told it to retain, the pipeline needs to run on every document insertion. In your codepen, you removed the stop word filter from the pipeline **after** the documents were added. In addition to this, but this is minor, `this` == `index` while in that closure.

I made the following changes to your codepen to get it to work:

- Moved the removal of the stop word filter to after the index definition
- Changed `index.pipeline.remove(...)` to `this.pipeline.remove(...)`

Let me know if this helped!
