### ISSUE TITLE
move to org

### ISSUE THREAD

**Issue by DanielRuf** [weixsong/elasticlunr.js#115]
This repository should be under an org account.

**Comment by srenauld** [comment]
Hey @DanielRuf!

I do agree with this, and I've been working on the new version on a different repo (this has taken a major back seat due to IRL issues, however). Could be something to consider.

As it stands, it's still a case of one person having publish rights on npm and no way to actually do anything else; AFAIK npm is still on `0.9.5` for example.

I'll just create an org for it next week if I can muster some time.

**Comment by edsu** [comment]
Yes, it looks like there are master commits from over a year ago that have never been released? There are probably enough users of this module to warrant an org approach.

**Comment by angristan** [comment]
http://elasticlunr.com/elasticlunr.min.js is also on `0.9.5`

**Comment by srenauld** [comment]
I'm done with the project that was taking the bulk of my time (I logged in 300+ hours each month in the past two months - firmware and hardware design and development). I'll have a lot more time for you guys now.

I'll create everything over the current week. Will ping when I'm done :-)
