### ISSUE TITLE
Incorrect partial matching

### ISSUE THREAD

**Issue by dilignt** [weixsong/elasticlunr.js#16]
Is it possible for elasticlunr to match partial words?  For example, if we run the example app and type in 'problem' there are lots of results.  But I would expect to get the same results when I type 'prob', 'probl' and 'proble' because the partial word does match content in the index.  Is this configurable?

In any case, it doesn't seem to work correctly.  I have a data set with many pages matching the word 'celebrate' - the results returned in include matches for 'celebrates', 'celebrated' and 'celebration'.  But when I type in 'celebr' I also get the matches as if partial matching does work, although when using 'celeb' or 'celebra' I get no matches.  Why is this?

I wanted to try elasticlunr because it creates a smaller index than lunr.js, although lunr.js allows partial matching which is what I need for my app, which returns new results on every character typed.  Does having the smaller index sacrifice partial matching?

**Comment by weixsong** [comment]
Hi, @dilignt , thanks very much for your feedback.

I have tested your cases. For query "celebra", elasticlunr does not return anything. but for query "celeb" it give some results. This behavior is because Elasticlunr add a stemmer in pipeline by default.
The stemmer pipeline will stem each word into its root format, this stemmer is used to increase the recall of query results.
Then for the query "celebra", stemmer doesn't know how to stem this word to its root, so it's keeped as "celebra", but in the index, 'celebrates', 'celebrated' and 'celebration', these words are stemmed to "celebr", so when query with "celebra", it will not found anything in index, but if you keep typing such as "celebrate", it will then query some documents out.
Lunr.js also use stemmer in it's pipeline by default.

As you want to use the query results as some hint for user, you could remove the stemmer in pipeline.
```javascript
var elasticlunr = function (config) {
  var idx = new elasticlunr.Index;

  idx.pipeline.add(
    elasticlunr.trimmer,
    elasticlunr.stopWordFilter,
    elasticlunr.stemmer
  );

  if (config) config.call(idx, idx);

  return idx;
};
```

**Comment by weixsong** [comment]
HI, @dilignt , I also tested with Lunr.js.

If your query with "celebra", Lunr.js also give no results.
```javascript
  var index = lunr(function () {
    this.field('title', {boost: 10})
    this.field('body')
    this.ref('id')
  })

  index.add({
    id: 1,
    title: 'celebrate  celebrates celebrated celebration',
  })

index.search('celebra')
```

results is:
<code>
[]
</code>

**Comment by dilignt** [comment]
@weixsong thanks for this clarification - I've clearly overlooked that my lunr setup has its stemmer removed
