### ISSUE TITLE
Fuzzy searching

### ISSUE THREAD

**Issue by atsepkov** [weixsong/elasticlunr.js#18]
Thanks for this search engine, I've added it to a mini web app I built and it works quite well. I was wondering if it's possible to do more "fuzzy" searches on the data that's indexed. For example, I log last accessed date for my documents and update it. If I could do the following search using the indexer, that would help me a lot:

    Find all documents that have access date greater than [timestamp]

Or, similar example in different context. Say I have a bunch of documents, each with a sentence like the following:

    99 bottles of beer on the wall
    98 bottles of beer on the wall
    ...
    10 bottles of beer on the wall

And I want to perform the following query:

    Find all documents where [## bottles of beer on the wall] > 50

**Comment by weixsong** [comment]
Hi, @atsepkov , thanks for using this package. 
Your suggestion is a good idea, but I think currently Elasticlunr could not support it because if we want to support your idea we need to change the data structure greatly.

Maybe in the future we could support your idea or if you get some time we hope that you could contribute your idea to this package.

Thanks.
