### ISSUE TITLE
Add multi-field search

### ISSUE THREAD

**Issue by jelovirt** [weixsong/elasticlunr.js#30]
Right now Elasticlunr will only search all fields with a the same query string. It would be beneficial if different query strings could be set per field. For example:

``` javascript
index.search({
    tag: "faq",
    body: "Oracle"
  }, {
    fields: {
      tag: {boost: 2},
      body: {boost: 1}
    },
    bool: "AND"
  });
```

That is, search both tag and body fields, but with different query terms. This would correspond the Lucene query syntax `tag:faq AND body:Oracle`.

AFAIC this would not need any modifications to the index and if the first argument to `search` could be an object instead of a simple String, existing code using the search would also be backwards compatible.

**Comment by weixsong** [comment]
Hi, @jelovirt , thanks very much for this brilliant idea. will support it in next release.

**Comment by playground** [comment]
Hi,
How do I form a query on multi fields?  Her is my use cases:
The documents consist of cityName, state, country, and bigCity fields where bigCity will be the city name if that city has population > 100,000 then cityName will be blank. Otherwise bigCity will be blank.

1) If a user keys in 'San Francisco,'  the result will match all cities with bigCity ranked top.

2) If the query is 'San Francisco CA' or 'San Francisco US' the result should just be 'San Francisco  CA'

3) If the query is 'San Francisco PT' the result should only be 'San Francisco PT' for Portugal 

Currently my query only successfully matches city name only scenario #1.  Every other combinations returns no result.
