### ISSUE TITLE
Index on all fields

### ISSUE THREAD

**Issue by Blahah** [weixsong/elasticlunr.js#6]
Is it possible to index on all fields? For example if I want to store documents that might not always have the same fields, but I want to be able to search across any or all fields.

**Comment by weixsong** [comment]
Yes, you could add a field named "all" or other name, and then extract all the content of your documents, then just index your documents by "all" field, then you could search in "all" field.
Actually, your request is a great idea for me, we could support a default "all" field that could support search for whole document.

**Comment by yangwen2** [comment]
From a performance perspective, do you recommend building the index across multiple fields or concatenate the content to a single field?  From my tests so far, for a multi-term search string, and when searching across ALL fields, the search result is much more predictable when the index consist of a single field versus multiple fields.

**Comment by weixsong** [comment]
@yangwen2 , from precision perspertive, I recommend to build index across multiple fields, but this need to adjust field weight manually or by experience, because some field such as title or keywords are much important than other fields.

But if you're not familiar with full-text search theory, just put all content in one field is also OK.
